DROP DATABASE IF EXISTS Image;
CREATE DATABASE Image;
USE Image;

CREATE TABLE image
(
id INT(10) PRIMARY KEY NOT NULL AUTO_INCREMENT,
name VARCHAR(10),
img BLOB,
width SMALLINT,
height SMALLINT,
treated VARCHAR(10) DEFAULT 'no'
)